import {__jacJsx, __jacSpawn} from "@jac-client/utils";
import { useRef } from "react";
import { Box, Paper, TextField, Button, Typography, Stack, Avatar, Divider, Fade, CircularProgress, Card, CardContent, Grow } from "@mui/material";
import { Send, School, Psychology, AutoAwesome, Clear, Person } from "@mui/icons-material";
function ChatTab(props) {
  let conversationHistory = props.conversationHistory;
  let message = props.message;
  let setMessage = props.setMessage;
  let loading = props.loading;
  let handleChat = props.handleChat;
  let handleKeyPress = props.handleKeyPress;
  let clearChat = props.clearChat;
  let messagesEndRef = props.messagesEndRef;
  let exampleQuestions = props.exampleQuestions;
  return __jacJsx(null, {}, [__jacJsx(Grow, {"in": true, "timeout": 800}, [__jacJsx(Paper, {"className": "glass-card glow", "elevation": 0, "sx": {"p": 4, "borderRadius": 0}}, [__jacJsx(Stack, {"direction": "row", "alignItems": "center", "spacing": 2, "justifyContent": "center"}, [__jacJsx(Avatar, {"sx": {"width": 64, "height": 64, "background": "linear-gradient(135deg, #a78bfa 0%, #f472b6 100%)", "boxShadow": "0 8px 32px rgba(167, 139, 250, 0.4)"}}, [__jacJsx(School, {"sx": {"fontSize": 36}}, [])]), __jacJsx(Box, {}, [__jacJsx(Typography, {"variant": "h3", "sx": {"background": "linear-gradient(135deg, #c4b5fd 0%, #f9a8d4 100%)", "WebkitBackgroundClip": "text", "WebkitTextFillColor": "transparent", "backgroundClip": "text", "textShadow": "0 0 40px rgba(167, 139, 250, 0.3)"}}, ["Smart Learning Companion"]), __jacJsx(Stack, {"direction": "row", "spacing": 1, "alignItems": "center", "sx": {"mt": 1}}, [__jacJsx(Psychology, {"sx": {"fontSize": 20, "color": "secondary.main"}}, []), __jacJsx(Typography, {"variant": "subtitle1", "color": "text.secondary", "sx": {"fontWeight": 500}}, ["Your AI-Powered Study Assistant"])])])])])]), __jacJsx(Grow, {"in": true, "timeout": 1000}, [__jacJsx(Paper, {"className": "glass-card", "elevation": 0, "sx": {"height": "calc(100vh - 300px)", "minHeight": "600px", "display": "flex", "flexDirection": "column", "overflow": "hidden", "borderRadius": 0}}, [__jacJsx(Box, {"sx": {"p": 3, "borderBottom": "1px solid rgba(167, 139, 250, 0.2)", "background": "linear-gradient(90deg, rgba(167, 139, 250, 0.1) 0%, rgba(244, 114, 182, 0.1) 100%)", "backdropFilter": "blur(10px)"}}, [__jacJsx(Stack, {"direction": "row", "justifyContent": "space-between", "alignItems": "center"}, [__jacJsx(Stack, {"direction": "row", "spacing": 1, "alignItems": "center"}, [__jacJsx(Psychology, {"color": "primary"}, []), __jacJsx(Typography, {"variant": "h5", "color": "primary"}, ["AI Tutor Chat"])]), conversationHistory.length > 0 ? __jacJsx(Button, {"variant": "outlined", "color": "error", "startIcon": __jacJsx(Clear, {}, []), "onClick": clearChat, "sx": {"borderRadius": 0}}, ["Clear Chat"]) : null])]), __jacJsx(Box, {"sx": {"flex": 1, "overflowY": "auto", "p": 3, "background": "transparent"}}, [conversationHistory.length > 0 ? __jacJsx(Stack, {"spacing": 2}, [conversationHistory.map(msg => {
    let isUser = msg["role"] === "user";
    return __jacJsx(Box, {"sx": {"display": "flex", "justifyContent": isUser ? "flex-end" : "flex-start", "mb": 2}, "key": msg["timestamp"]}, [__jacJsx(Fade, {"in": true, "timeout": 300}, [__jacJsx(Card, {"className": isUser ? "message-slide-right" : "message-slide-left", "sx": {"maxWidth": "75%", "background": isUser ? "linear-gradient(135deg, #a78bfa 0%, #f472b6 100%)" : "rgba(30, 41, 59, 0.8)", "color": "white", "backdropFilter": "blur(20px)", "border": isUser ? "1px solid rgba(167, 139, 250, 0.3)" : "1px solid rgba(203, 213, 225, 0.2)", "boxShadow": isUser ? "0 8px 32px rgba(167, 139, 250, 0.3)" : "0 8px 32px rgba(0, 0, 0, 0.2)", "borderRadius": "20px", "borderBottomRightRadius": isUser ? "4px" : "20px", "borderBottomLeftRadius": isUser ? "20px" : "4px"}}, [__jacJsx(CardContent, {"sx": {"p": 2, "&:last-child": {"pb": 2}}}, [__jacJsx(Stack, {"spacing": 1}, [__jacJsx(Stack, {"direction": "row", "spacing": 1, "alignItems": "center"}, [__jacJsx(Avatar, {"sx": {"width": 28, "height": 28, "background": isUser ? "rgba(255, 255, 255, 0.2)" : "rgba(167, 139, 250, 0.3)"}}, [isUser ? __jacJsx(Person, {"sx": {"fontSize": 18}}, []) : __jacJsx(Psychology, {"sx": {"fontSize": 18}}, [])]), __jacJsx(Typography, {"variant": "caption", "sx": {"fontWeight": 600, "opacity": 0.9}}, [isUser ? "You" : "AI Tutor"])]), __jacJsx(Typography, {"variant": "body1", "sx": {"lineHeight": 1.6, "whiteSpace": "pre-wrap", "wordBreak": "break-word"}}, [msg["content"]])])])])])]);
  }), loading ? __jacJsx(Fade, {"in": true, "timeout": 300}, [__jacJsx(Box, {"sx": {"display": "flex", "justifyContent": "flex-start"}}, [__jacJsx(Card, {"sx": {"maxWidth": "75%", "background": "#ffffff", "borderRadius": "20px"}}, [__jacJsx(CardContent, {"sx": {"p": 2, "&:last-child": {"pb": 2}}}, [__jacJsx(Stack, {"direction": "row", "spacing": 1, "alignItems": "center"}, [__jacJsx(CircularProgress, {"size": 20}, []), __jacJsx(Typography, {"color": "text.primary"}, ["AI is thinking..."])])])])])]) : null, __jacJsx("div", {"ref": messagesEndRef}, [])]) : __jacJsx(Box, {"sx": {"display": "flex", "flexDirection": "column", "alignItems": "center", "justifyContent": "center", "height": "100%", "textAlign": "center"}}, [__jacJsx(Fade, {"in": true, "timeout": 500}, [__jacJsx(Box, {}, [__jacJsx(Psychology, {"className": "pulse", "sx": {"fontSize": 120, "color": "primary.main", "mb": 3, "filter": "drop-shadow(0 0 30px rgba(167, 139, 250, 0.3))"}}, []), __jacJsx(Typography, {"variant": "h4", "gutterBottom": true, "sx": {"fontWeight": 700, "color": "primary.main"}}, ["Start a Conversation"]), __jacJsx(Typography, {"color": "text.secondary", "sx": {"mb": 4, "maxWidth": 500}}, ["Ask me anything! I'm here to help you learn and understand complex topics."]), __jacJsx(Box, {"sx": {"maxWidth": 600, "mx": "auto"}}, [__jacJsx(Typography, {"variant": "subtitle2", "sx": {"mb": 2, "fontWeight": 600, "color": "primary.light"}}, ["Try these examples:"]), __jacJsx(Stack, {"spacing": 1}, [exampleQuestions.map(question => {
    return __jacJsx(Paper, {"key": question, "onClick": () => {
      setMessage(question);
    }, "sx": {"p": 2, "cursor": "pointer", "border": "1px solid rgba(167, 139, 250, 0.2)", "background": "rgba(167, 139, 250, 0.05)", "&:hover": {"background": "rgba(167, 139, 250, 0.1)", "borderColor": "primary.main"}}}, [__jacJsx(Typography, {"variant": "body2"}, [question])]);
  })])])])])])]), __jacJsx(Divider, {"sx": {"borderColor": "rgba(167, 139, 250, 0.2)"}}, []), __jacJsx(Box, {"sx": {"p": 3, "background": "rgba(15, 23, 42, 0.5)", "backdropFilter": "blur(10px)"}}, [__jacJsx(Stack, {"spacing": 2}, [__jacJsx(TextField, {"fullWidth": true, "multiline": true, "rows": 3, "value": message, "onChange": e => {
    setMessage(e.target.value);
  }, "onKeyPress": handleKeyPress, "placeholder": "Type your question here... (Shift+Enter for new line, Enter to send)", "disabled": loading, "variant": "outlined"}, []), __jacJsx(Button, {"fullWidth": true, "variant": "contained", "size": "large", "onClick": handleChat, "disabled": loading || !message.trim(), "startIcon": loading ? __jacJsx(CircularProgress, {"size": 20, "sx": {"color": "white"}}, []) : __jacJsx(Send, {}, []), "sx": {"py": 1.5, "background": "linear-gradient(135deg, #a78bfa 0%, #f472b6 100%)", "&:hover": {"background": "linear-gradient(135deg, #c4b5fd 0%, #f9a8d4 100%)"}}}, [loading ? "Sending..." : "Send Message"])])])])]), __jacJsx(Typography, {"variant": "body2", "align": "center", "sx": {"color": "rgba(248, 250, 252, 0.7)", "fontWeight": 500, "textShadow": "0 0 20px rgba(167, 139, 250, 0.3)"}}, ["\u26a1 Powered by GPT-4o \u2022 Built with Jaclang & Material-UI"])]);
}
export { ChatTab };
